# Generated by Django 5.2.3 on 2025-07-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="watchAgain",
        ),
    ]
